# Generated by Django 6.0.2 on 2026-02-05 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a brief, descriptive title for your task', max_length=200, verbose_name='Task Title')),
                ('description', models.TextField(blank=True, help_text='Add more details about your task (optional)', null=True, verbose_name='Description')),
                ('completed', models.BooleanField(default=False, help_text='Mark as completed when task is done', verbose_name='Completed')),
                ('priority', models.IntegerField(choices=[(1, '⭐ Very Low'), (2, '⭐⭐ Low'), (3, '⭐⭐⭐ Medium'), (4, '⭐⭐⭐⭐ High'), (5, '⭐⭐⭐⭐⭐ Critical')], default=3, help_text='Select priority from 1 (lowest) to 5 (highest)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Priority Level')),
                ('due_date', models.DateField(blank=True, help_text='Set a deadline for this task (optional)', null=True, verbose_name='Due Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Todo Item',
                'verbose_name_plural': 'Todo Items',
                'ordering': ['-priority', 'completed', 'due_date'],
            },
        ),
    ]
