# Generated by Django 6.0.2 on 2026-03-13 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todo_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short, descriptive name (e.g., Work, Personal)', max_length=100, verbose_name='Category Name')),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for the category badge (e.g., #28a745)', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.AddField(
            model_name='todo',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Select one or more categories for this task', related_name='todos', to='todos.category', verbose_name='Categories'),
        ),
    ]
